Repository MafiaHub/MafiaMP, pull requests merged in 2024-01, with the labels that each got.

#30 Radio sync
  code/client/src/core/modules/vehicle.cpp
  code/server/src/core/builtins/vehicle.h
  code/shared/game_rpc/tune_radio.h
  code/shared/modules/vehicle_sync.hpp
Labels: enhancement

#33 Partial state updates
  code/client/src/core/modules/human.cpp
  code/client/src/core/modules/vehicle.cpp
  code/server/src/core/builtins/player.h
  code/server/src/core/builtins/vehicle.h
  code/server/src/core/modules/vehicle.cpp
  code/server/src/core/modules/vehicle.h
  code/shared/game_rpc/human/human_setprops.h
  code/shared/game_rpc/tune_radio.h
  code/shared/game_rpc/vehicle/vehicle_setprops.h
  code/shared/messages/vehicle/vehicle_spawn.h
  code/shared/modules/vehicle_sync.hpp
Labels: enhancement

#35 Initial work for C_VehiclesDatabase
  code/client/CMakeLists.txt
  code/client/src/core/dev_features.cpp
  code/client/src/core/dev_features.h
  code/client/src/sdk/mafia/framework/c_mafia_dbs.cpp
  code/client/src/sdk/mafia/framework/c_mafia_dbs.h
  code/client/src/sdk/mafia/framework/c_vehicles_database.cpp
  code/client/src/sdk/mafia/framework/c_vehicles_database.h
  code/client/src/sdk/mafia/tables/table_defines.h
  code/client/src/sdk/mafia/tables/vehicle/vehicle_defines.h
  code/client/src/sdk/mafia/traffic/traffic_defines.h
  code/client/src/sdk/patterns.cpp
  code/client/src/sdk/patterns.h
  code/client/src/sdk/ue/c_weak_ptr.h
  code/client/src/sdk/ue/sys/sodb/c_database_interface.h
  code/client/src/sdk/ue/sys/sodb/c_database_system.cpp
  code/client/src/sdk/ue/sys/sodb/c_database_system.h
  code/client/src/sdk/ue/sys/sodb/c_sys_odb.h
Labels: enhancement

#37 Fix corrupted event call arg stack issue
  code/server/src/core/builtins/player.h
  code/server/src/core/server.cpp
  code/server/src/core/server.h
Labels: enhancement

#44 Vehicle DB improvements
  code/client/src/core/dev_features.cpp
  code/client/src/sdk/gamedb/tables/vehicles/s_vehicles_table_item.h
  code/client/src/sdk/mafia/framework/c_vehicles_database.h
  code/client/src/sdk/ue/c_weak_ptr.h
  code/client/src/sdk/ue/sys/sodb/c_database_interface.h
Labels: enhancement

#70 Fix Revert "Vehicle DB improvements (#44)"
  code/client/src/core/dev_features.cpp
  code/client/src/sdk/gamedb/tables/vehicles/s_vehicles_table_item.h
  code/client/src/sdk/mafia/framework/c_vehicles_database.cpp
  code/client/src/sdk/mafia/framework/c_vehicles_database.h
  code/client/src/sdk/ue/c_weak_ptr.h
  code/client/src/sdk/ue/sys/sodb/c_database_interface.h
  code/client/src/sdk/ue/sys/sodb/c_database_system.cpp
  code/client/src/sdk/ue/sys/sodb/c_database_system.h
  code/client/src/sdk/ue/sys/sodb/c_sys_odb.h
Labels: priority:high

#64 Reverse more WeatherManager2 stuffs
  code/client/src/sdk/patterns.cpp
  code/client/src/sdk/patterns.h
  code/client/src/sdk/ue/gfx/environmenteffects/c_weather_manager_2.cpp
  code/client/src/sdk/ue/gfx/environmenteffects/c_weather_manager_2.h
  code/server/src/core/server.cpp
Labels: priority:medium

#75 Data compression
  code/client/src/core/modules/vehicle.cpp
  code/server/src/core/builtins/vehicle.h
  code/shared/game_rpc/set_vehicledata.h
  code/shared/messages/human/human_spawn.h
  code/shared/messages/human/human_update.h
  code/shared/messages/vehicle/vehicle_owner_update.h
  code/shared/messages/vehicle/vehicle_spawn.h
  code/shared/messages/vehicle/vehicle_update.h
Labels: enhancement, priority:low

#77 chat history
  code/client/src/core/ui/chat.cpp
  code/client/src/core/ui/chat.h
Labels: enhancement, priority:low
